const BACKGROUND_DARK = '#2e2e2e';
const BACKGROUND_LIGHT = '#faf9f7';

const FONT_DARK = '#2e2e2e';
const FONT_LIGHT = '#faf9f7';

export { BACKGROUND_DARK, BACKGROUND_LIGHT, FONT_DARK, FONT_LIGHT };
